name: 'Run tests'

on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create venv
        run: |
          python3 -m venv venv
          . ./venv/bin/activate
          pip install --no-cache poetry==2.2.1 && \
          poetry config virtualenvs.create false && \
          poetry install --no-cache --with dev

      - name: Run tests
        run: |
          set -e
          . ./venv/bin/activate
          black --check .
          pylint *.py deps
